### ISSUE TITLE
Migrate to bitnami/phppgadmin

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/docker-compose-demo#212]
Recently, Bitnami has created a `phppgadmin` container (https://hub.docker.com/r/bitnami/phppgadmin).

With that in mind, change the `phppgadmin:` service to the following:

```yaml
  phppgadmin:
    container_name: senzing-phppgadmin
    environment:
#     See https://hub.docker.com/r/bitnami/phppgadmin
      - DATABASE_HOST=senzing-postgres
    image: bitnami/phppgadmin:${SENZING_DOCKER_IMAGE_VERSION_BITNAMI_PHPPGADMIN:-latest}
    networks:
      - backend
    ports:
      - 9171:8080
      - 9172:443
    restart: always
```
